// for Product page REDUCER
export const GET_PRODUCT_REQUEST = 'GET_PRODUCT_REQUEST'
export const GET_PRODUCT_SUCCESS = 'GET_PRODUCT_SUCCESS'
export const GET_PRODUCT_FAILURE = 'GET_PRODUCT_FAILURE'

export const GET_SINGLE_PRODUCT_SUCCESS = 'GET_SINGLE_PRODUCT_SUCCESS'



// for cart page REDUCER
export const GET_CART_REQUEST = 'GET_CART_REQUEST'
export const GET_CART_SUCCESS = 'GET_CART_SUCCESS'
export const GET_CART_FAILURE = 'GET_CART_FAILURE'
export const POST_CART_PRODUCT = 'POST_CART_PRODUCT'
export const DELETE_CART_PRODUCT = 'DELETE_CART_PRODUCT'



// for Account page REDUCER
export const POST_NEW_USER = 'POST_NEW_USER'
export const GET_CURRENT_USER = 'GET_CURRENT_USER' 
